### ISSUE TITLE
Separate specification for scanner and parser or combined one?

### ISSUE THREAD

**Issue by BjoernLoetters** [zen-pie/macrowave#1]
#### Description
There are two specifications: one for the scanner and one for the parser. They're completely decoupled and can be freely exchanged with other tools. The scanner produces a stream of tokens of arbitrary type. An internal mapping from type to integer is necessary to index the parse table. This is caused by the fact that terminal symbols (i.e. tokens) are values of arbitrary type. However, the index must be an integer.

#### Pros
- Scanner and parser are completely decoupled and may be exchanged with other tools.

#### Cons
- The parser is slightly slower, because of the fact that it needs to lookup an index based on an arbitrary type.
- To solve the previous disadvantage, the user could explicitly declare the tokens. This would entail that the scanner produces a stream of integers. A loss of abstraction would be the result.

#### Description
There is one specification for both, the parser and the scanner. Similar to the [scala parser combinators](https://github.com/scala/scala-parser-combinators) the user does not have to bother with a scanner. Nevertheless a scanner is generated under the hood which is able to recognize the tokens.

#### Pros
- The parser is faster than the one from the first proposal. This is caused by the fact, that the scanner is not visible to the user and may therefore produce a stream of integers. No extra lookup is necessary to index the parse table.

#### Cons
- It is not possible to use the scanner without generating a parser (although a parser is at least as powerful as a scanner, but not as fast).

**Comment by BjoernLoetters** [comment]
I think we should go for the combined specification. There is no need to bother with a scanner in these days (expect some special cases) when a parser can do the same.

**Comment by keddelzz** [comment]
I never had to implement a scanner without a parser, therefore I think we should implement a PEG-(like-)library (combined specification), instead of a scanner- and parser-generator (separate specification).

**Comment by keddelzz** [comment]
> To solve the previous disadvantage, the user could explicitly declare the tokens. This would entail that the scanner produces a stream of integers. A loss of abstraction would be the result.

Also, I don't want to tell the compiler, which tokens my language has. My computer can find that out automatically.

**Comment by BjoernLoetters** [comment]
We have to unify both ideas. The scanner needs a user defined conflict resolution (e.g. the tokens "for" and ".+" need an explicit order, otherwise a wrong token may be returned).

I'd recommend the following syntax:

```scala
@grammar
class MyParser {
  /* Tokens (order matters) */
  val forKeyword = token("for")
  val ifKeyword = token("if")
  val identifier = token(regex("[a-zA-Z_][a-zA-Z_]*")) // identifier also matches `for` and `if`
  // ...
  /* Rules */
  def ruleS = forKeyword ~ identifier ~ ifKeyword ~ identifier // calling `token` is not allowed here
}
```

**Comment by keddelzz** [comment]
We decided to define parser and scanner in one grammar-file. I'm closing this issue now!
